### ISSUE TITLE
Dependency list in README.md page is outdated. 

### ISSUE THREAD

**Issue by ericho** [intel-ctrlsys/sensys#3]
The dependency list is outdated and a little confusing. We should separate dependencies that are available on supported OS from the remaining ones.

**Comment by Jaysawn** [comment]
Even though there is a note above the dependency list for 'full support', I think it would be nice to have a list that is actually required and a list that are only required for additional functionality.

**Comment by ericho** [comment]
Thanks @Jaysawn, that's a good idea.

So we might need to define a **base** version of Sensys and then add requirements for specific functionality. 

Probably we also might need a *Compilation guide* with the of the requirements for specific features.

**Comment by ericho** [comment]
The dependency list was updated on this commit e1666389d '
