### ISSUE TITLE
Sensys needs a Getting Started page

### ISSUE THREAD

**Issue by ericho** [intel-ctrlsys/sensys#8]
In order to help users to get a first touch of Sensys, the Getting Started section in the README.md needs to be improved. The goal of a Getting Started section is to have the basic usage of the system in which the main functionality can be seen and tested by the users.

We need to define the scope of this section, if we execute the system in only one node or provide an example with a bigger number of nodes, or maybe both 😄 

If the Getting Started section grows significantly (probably it will) then we can consider to create a new page only for this.

**Comment by vrescami** [comment]
Here is some information I'd like to see in that page:

1. Download and installation (how to compile it, perhaps?).
2. Steps to run a sensor on single node. Either freq, coretemp or componentpower should work.
3. Steps to create an udsensor and run it.
4. Link metrics to database using postgresql.
5. Introduce the aggregator and multinode execution.

**Comment by ericho** [comment]
Thanks @VicsEscamilla !

The Getting Started page was [added to the sensys-doc repository](https://github.com/intel-ctrlsys/sensys-doc/blob/master/src/gettingStarted.md). And the [documentation page](https://intel-ctrlsys.github.io/sensys/gettingStarted.html) was updated with the new changes.

Closing this issue as it is solved :smile:
